name: Build styleguide

on: workflow_dispatch

env:
    LATEST_VERSION: '2.1'
    AVAILABLE_VERSIONS: '["master", "2.1", "2.0"]'

jobs:
    build-styleguide:
        name: Build styleguide
        runs-on: ubuntu-latest

        strategy:
            matrix:
                version:
                    - { ref: 'master', version: 'latest' }
                    - { ref: 'release/2.1', version: '2.1' }
                    - { ref: 'release/2.0', version: '2.0' }

        steps:
            - run: echo Building styleguide for version "${{ matrix.version.version }}" from ref "${{ matrix.version.ref }}"

            - name: Checkout project
              uses: actions/checkout@v2

            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Build styleguide
              run: bin/build-styleguide ${{ matrix.version.ref }} ${{ matrix.version.version }} "$AVAILABLE_VERSIONS"

            - name: Push styleguide
              run: |
                  git pull --ff-only
                  git config user.email "github@sulu.io"
                  git config user.name "Sulu User"
                  git add docs/${{ matrix.version.version }}
                  git status
                  git diff --quiet && git diff --staged --quiet || git commit -m "Publish '${{ matrix.version.version }}'"
                  git push || (git pull --rebase && git push)

    update-index:
        name: Update index.html file
        runs-on: ubuntu-latest
        needs: build-styleguide

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Pull repository
              run: git pull --ff-only

            - name: Update index.html
              run: echo "<!DOCTYPE html><html><body><script>window.location.href += '/$LATEST_VERSION';</script></body></html>" > docs/index.html

            - name: Push index.html
              run: |
                  git config user.email "github@sulu.io"
                  git config user.name "Sulu User"
                  git add docs/index.html
                  git status
                  git diff --quiet && git diff --staged --quiet || git commit -m "Update index.html file"
                  git push || (git pull --rebase && git push)
